// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NguyenVanThinh_BaiTap.Data;

#nullable disable

namespace NguyenVanThinh_BaiTap.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_ChiTietDonHang", b =>
                {
                    b.Property<int>("Thinh_ChiTietDonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Thinh_ChiTietDonHangID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Thinh_DonHangID")
                        .HasColumnType("int");

                    b.Property<int>("Thinh_XeID")
                        .HasColumnType("int");

                    b.HasKey("Thinh_ChiTietDonHangID");

                    b.HasIndex("Thinh_DonHangID");

                    b.HasIndex("Thinh_XeID");

                    b.ToTable("Thinh_ChiTietDonHang");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_DonHang", b =>
                {
                    b.Property<int>("Thinh_DonHangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Thinh_DonHangID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaDonHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Thinh_DonHangID");

                    b.ToTable("Thinh_DonHang");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_HangXe", b =>
                {
                    b.Property<int>("Thinh_HangXeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Thinh_HangXeID"));

                    b.Property<string>("Thinh_TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Thinh_HangXeID");

                    b.ToTable("Thinh_HangXe");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_Xe", b =>
                {
                    b.Property<int>("Thinh_XeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Thinh_XeID"));

                    b.Property<decimal>("Thinh_Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Thinh_HangXeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thinh_NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Thinh_TenXe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Thinh_XeID");

                    b.HasIndex("Thinh_HangXeID");

                    b.ToTable("Thinh_Xe");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_ChiTietDonHang", b =>
                {
                    b.HasOne("NguyenVanThinh_BaiTap.Models.Thinh_DonHang", "Thinh_DonHang")
                        .WithMany("Thinh_ChiTietDonHang")
                        .HasForeignKey("Thinh_DonHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NguyenVanThinh_BaiTap.Models.Thinh_Xe", "Thinh_Xe")
                        .WithMany("Thinh_ChiTietDonHang")
                        .HasForeignKey("Thinh_XeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thinh_DonHang");

                    b.Navigation("Thinh_Xe");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_Xe", b =>
                {
                    b.HasOne("NguyenVanThinh_BaiTap.Models.Thinh_HangXe", "Thinh_HangXe")
                        .WithMany("Thinh_Xe")
                        .HasForeignKey("Thinh_HangXeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thinh_HangXe");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_DonHang", b =>
                {
                    b.Navigation("Thinh_ChiTietDonHang");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_HangXe", b =>
                {
                    b.Navigation("Thinh_Xe");
                });

            modelBuilder.Entity("NguyenVanThinh_BaiTap.Models.Thinh_Xe", b =>
                {
                    b.Navigation("Thinh_ChiTietDonHang");
                });
#pragma warning restore 612, 618
        }
    }
}
